### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel. 

### ISSUE THREAD

**Issue by pattilca** [Chem4Word/Version3#24]
**Describe the bug**
I am trying to use the pubchem search in the latest version of Chem4word and am getting the following error:
The request was aborted: Could not create SSL/TLS secure channel. 
Please advice.  Thanks

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to puchem search
2. Enter any chemical name
3. See error:  The request was aborted: Could not create SSL/TLS secure channel. 

**Expected behavior**
I expect the pubchem search to produce a result

**CML Data**
```xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Please paste the cml of your structure here -->
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Word Version Office Pro
 - Please also gather system information from "Help" --> "System Info" in Chem4Word Ribbon

**Additional context**

**Comment by MikeWilliams-UK** [comment]
Thanks for confirming which version you are using.

The images, which I think that you attached while replying to the notification email have been corrupted, please go to GitHub issue and paste them there again.

**Comment by MikeWilliams-UK** [comment]
Hi Pat Atkins,

Could you please tell us what search term you have been using?

Could you please use the GitHub website to post your screen shot (s) again as it/they seem to have been corrupted.

When you next get our error dialogue, please fill in your ail address. The system will then send us additional information which may enable us to diagnose your issue.

**Comment by MikeWilliams-UK** [comment]
Hi Patricia,

Thankyou for taking the time to report the bug, we will get that fixed as soon as possble.

In the mean time you can upgrade to Chem4Word Version 2020 in which the issue is fixed.
This is a free upgrade and you will not lose any data.

The installer can be found here https://github.com/Chem4Word/Version3-1/releases/latest.

/Mike

**Comment by pattilca** [comment]
Hello Mike

I downloaded the new version and am still getting an error when searching pubchem.  The other two searches work.

[cid:image001.jpg@01D6EDA3.E03F5F30]

Patricia Atkins

**Comment by MikeWilliams-UK** [comment]
I tried it out on my Azure virtual machine running Windows 10 pro with office 365 this morning.

When I ran V3 it gave me the same errors as you are seeing.
When I installed V2020 pubchem searches worked fine.

Can you tell me which search terms still fail for your with V2020 please?

**Comment by pattilca** [comment]
All searches fail.  I tried simple chemicals just to see if it worked like Heptane, hexane, methanol, acetone all failed.

**Comment by MikeWilliams-UK** [comment]
Which anti virus program do you use?

Could you try turning it off (especially scanning and firewall) to see if it is interfering with network requests?

Now that you are running Version 2020, can you use Help -> System Info to get some debugging info for us.
The data here is copy paste friendly so should be easy to paste here.

**Comment by pattilca** [comment]
Hello

I know that heptane should work fine but no matter what search term I enter I get the error:  The request was aborted: The connection was closed unexpectedly.

[cid:image001.jpg@01D6EE82.964EE3C0]

As for the Help About – here is what I have:
[cid:image002.jpg@01D6EE82.964EE3C0]

As for the System info:

Chem4Word 2020 Release 6 - [3.1.16.7656]

Installation Id: 46f7d015-45b8-45a3-b280-1b81c6248d06
Operating System: Microsoft Windows 10 Enterprise 64bit [10.0.17763.0] en-US
Word Product: Microsoft Office 365 Professional Plus 32bit [16.0.13530.20376]
Internet Explorer Version: 11.0.17763.379
.Net Framework Runtime: .NET 4.8 [528049]

Settings Folder: C:\Users\patkins\AppData\Local\Chem4Word.V3
Library Folder: C:\ProgramData\Chem4Word.V3

PlugIns Folder: C:\Program Files (x86)\Chem4Word V3\PlugIns
  Chem4Word.Editor.ACME.dll - [3.1.16.7656]
  Chem4Word.Editor.ChemDoodleWeb800.dll - [3.1.16.7656]
  Chem4Word.Renderer.OoXmlV4.dll - [3.1.16.7656]
  Chem4Word.Searcher.ChEBIPlugin.dll - [3.1.16.7656]
  Chem4Word.Searcher.OpsinPlugIn.dll - [3.1.16.7656]
  Chem4Word.Searcher.PubChemPlugIn.dll - [3.1.16.7656]

.Net Assemblies loaded in memory
  Accessibility, Version=4.0.0.0
  Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0
  Chem4Word.ACME, Version=3.1.16.7656
  Chem4Word.Core, Version=3.1.16.7656
  Chem4Word.Editor.ACME, Version=3.1.16.7656
  Chem4Word.Editor.ChemDoodleWeb800, Version=3.1.16.7656
  Chem4Word.Model2, Version=3.1.16.7656
  Chem4Word.Renderer.OoXmlV4, Version=3.1.16.7656
  Chem4Word.Searcher.ChEBIPlugin, Version=3.1.16.7656
  Chem4Word.Searcher.OpsinPlugIn, Version=3.1.16.7656
  Chem4Word.Searcher.PubChemPlugIn, Version=3.1.16.7656
  Chem4Word.Telemetry, Version=3.1.16.7656
  Chem4Word.V3, Version=3.1.16.7656
  CustomMarshalers, Version=4.0.0.0
  IChem4Word.Contracts, Version=3.1.16.7656
  Microsoft.CSharp, Version=4.0.0.0
  Microsoft.Office.Interop.Word, Version=15.0.0.0
  Microsoft.Office.Tools, Version=10.0.0.0
  Microsoft.Office.Tools.Common, Version=10.0.0.0
  Microsoft.Office.Tools.Common.Implementation, Version=10.0.0.0
  Microsoft.Office.Tools.Common.v4.0.Utilities, Version=10.0.0.0
  Microsoft.Office.Tools.Word, Version=10.0.0.0
  Microsoft.Office.Tools.Word.Implementation, Version=10.0.0.0
  Microsoft.ServiceBus, Version=3.0.0.0
  Microsoft.VisualStudio.Tools.Applications.Runtime, Version=10.0.0.0
  Microsoft.VisualStudio.Tools.Applications.ServerDocument, Version=10.0.0.0
  Microsoft.VisualStudio.Tools.Office.Runtime, Version=10.0.0.0
  mscorlib, Version=4.0.0.0
  Newtonsoft.Json, Version=12.0.0.0
  office, Version=15.0.0.0
  PresentationCore, Version=4.0.0.0
  PresentationFramework, Version=4.0.0.0
  PresentationFramework.Aero2, Version=4.0.0.0
  SMDiagnostics, Version=4.0.0.0
  System, Version=4.0.0.0
  System.Configuration, Version=4.0.0.0
  System.Core, Version=4.0.0.0
  System.Data, Version=4.0.0.0
  System.Drawing, Version=4.0.0.0
  System.Dynamic, Version=4.0.0.0
  System.EnterpriseServices, Version=4.0.0.0
  System.IdentityModel, Version=4.0.0.0
  System.IdentityModel.Tokens.Jwt, Version=6.7.1.0
  System.Management, Version=4.0.0.0
  System.Numerics, Version=4.0.0.0
  System.Runtime.Caching, Version=4.0.0.0
  System.Runtime.Serialization, Version=4.0.0.0
  System.ServiceModel, Version=4.0.0.0
  System.ServiceModel.Internals, Version=4.0.0.0
  System.Transactions, Version=4.0.0.0
  System.Web, Version=4.0.0.0
  System.Web.Services, Version=4.0.0.0
  System.Windows.Forms, Version=4.0.0.0
  System.Xaml, Version=4.0.0.0
  System.Xml, Version=4.0.0.0
  System.Xml.Linq, Version=4.0.0.0
  UIAutomationProvider, Version=4.0.0.0
  UIAutomationTypes, Version=4.0.0.0
  WindowsBase, Version=4.0.0.0
  WindowsFormsIntegration, Version=4.0.0.0
